// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvwtvpvqomavvmhhroyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2d3R2cHZxb21hdnZtaGhyb3lkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MTc5NjIsImV4cCI6MjA3MjA5Mzk2Mn0.Be2Dshy1spOkJyn4STwnjkSBrsxJ5VtiLcTdyw-zIjI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});